### ISSUE TITLE
Not all spigot.yml configs are working

### ISSUE THREAD

**Issue by evernife** [CrucibleMC/Crucible#28]
A few `spigot.yml` configs are not working. 

For example merge-radius, 
```
world-settings:
  default:
    merge-radius:
      item: 10.5
      exp: 10.0
```

The ITEM merge is not working, while the EXP merge is working.

```
world-settings:
  default:
    entity-tracking-range:
      players: 10
      animals: 10
      monsters: 10
      misc: 10
      other: 10
    entity-activation-range:
      animals: 5
      monsters: 5
      misc: 5
```
Entity-tracking-range is working, while entity-activation-range is not.

And a few more tests are needed.
